// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (tenant_id, name, key_id, secret_hash, secret_enc) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id, tenant_id, name, key_id, secret_hash, secret_enc, active, created_at, last_used_at
`

type CreateAPIKeyParams struct {
	TenantID   pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Name       string      `db:"name" json:"name"`
	KeyID      string      `db:"key_id" json:"key_id"`
	SecretHash string      `db:"secret_hash" json:"secret_hash"`
	SecretEnc  []byte      `db:"secret_enc" json:"secret_enc"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.TenantID,
		arg.Name,
		arg.KeyID,
		arg.SecretHash,
		arg.SecretEnc,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyID,
		&i.SecretHash,
		&i.SecretEnc,
		&i.Active,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, tenant_id, name, key_id, secret_hash, secret_enc, active, created_at, last_used_at FROM api_keys 
WHERE id = $1 AND active = TRUE
`

func (q *Queries) GetAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyID,
		&i.SecretHash,
		&i.SecretEnc,
		&i.Active,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByKeyID = `-- name: GetAPIKeyByKeyID :one
SELECT id, tenant_id, name, key_id, secret_hash, secret_enc, active, created_at, last_used_at FROM api_keys 
WHERE key_id = $1 AND active = TRUE
`

func (q *Queries) GetAPIKeyByKeyID(ctx context.Context, keyID string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByKeyID, keyID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyID,
		&i.SecretHash,
		&i.SecretEnc,
		&i.Active,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByTenant = `-- name: GetAPIKeyByTenant :one
SELECT id, tenant_id, name, key_id, secret_hash, secret_enc, active, created_at, last_used_at FROM api_keys 
WHERE tenant_id = $1 AND id = $2 AND active = TRUE
`

type GetAPIKeyByTenantParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	ID       pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAPIKeyByTenant(ctx context.Context, arg GetAPIKeyByTenantParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByTenant, arg.TenantID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyID,
		&i.SecretHash,
		&i.SecretEnc,
		&i.Active,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys 
SET last_used_at = NOW() 
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
