// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flag_rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlagRule = `-- name: CreateFlagRule :one
INSERT INTO flag_rules (flag_id, priority, rollout, variant) 
VALUES ($1, $2, $3, $4) 
RETURNING id, flag_id, priority, rollout, variant, updated_at
`

type CreateFlagRuleParams struct {
	FlagID   pgtype.UUID `db:"flag_id" json:"flag_id"`
	Priority int32       `db:"priority" json:"priority"`
	Rollout  int32       `db:"rollout" json:"rollout"`
	Variant  []byte      `db:"variant" json:"variant"`
}

func (q *Queries) CreateFlagRule(ctx context.Context, arg CreateFlagRuleParams) (FlagRule, error) {
	row := q.db.QueryRow(ctx, createFlagRule,
		arg.FlagID,
		arg.Priority,
		arg.Rollout,
		arg.Variant,
	)
	var i FlagRule
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.Priority,
		&i.Rollout,
		&i.Variant,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlagRule = `-- name: DeleteFlagRule :exec
DELETE FROM flag_rules 
WHERE flag_id = $1 AND priority = $2
`

type DeleteFlagRuleParams struct {
	FlagID   pgtype.UUID `db:"flag_id" json:"flag_id"`
	Priority int32       `db:"priority" json:"priority"`
}

func (q *Queries) DeleteFlagRule(ctx context.Context, arg DeleteFlagRuleParams) error {
	_, err := q.db.Exec(ctx, deleteFlagRule, arg.FlagID, arg.Priority)
	return err
}

const getRulesByFlag = `-- name: GetRulesByFlag :many
SELECT id, flag_id, priority, rollout, variant, updated_at FROM flag_rules 
WHERE flag_id = $1 
ORDER BY priority ASC
`

func (q *Queries) GetRulesByFlag(ctx context.Context, flagID pgtype.UUID) ([]FlagRule, error) {
	rows, err := q.db.Query(ctx, getRulesByFlag, flagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlagRule{}
	for rows.Next() {
		var i FlagRule
		if err := rows.Scan(
			&i.ID,
			&i.FlagID,
			&i.Priority,
			&i.Rollout,
			&i.Variant,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlagRule = `-- name: UpdateFlagRule :one
UPDATE flag_rules 
SET rollout = COALESCE($3, rollout),
    variant = COALESCE($4, variant)
WHERE flag_id = $1 AND priority = $2
RETURNING id, flag_id, priority, rollout, variant, updated_at
`

type UpdateFlagRuleParams struct {
	FlagID   pgtype.UUID `db:"flag_id" json:"flag_id"`
	Priority int32       `db:"priority" json:"priority"`
	Rollout  int32       `db:"rollout" json:"rollout"`
	Variant  []byte      `db:"variant" json:"variant"`
}

func (q *Queries) UpdateFlagRule(ctx context.Context, arg UpdateFlagRuleParams) (FlagRule, error) {
	row := q.db.QueryRow(ctx, updateFlagRule,
		arg.FlagID,
		arg.Priority,
		arg.Rollout,
		arg.Variant,
	)
	var i FlagRule
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.Priority,
		&i.Rollout,
		&i.Variant,
		&i.UpdatedAt,
	)
	return i, err
}
