// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flag_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssignment = `-- name: GetAssignment :one
SELECT id, flag_id, subject_id, bucket, chosen_variant, assigned_at FROM flag_assignments 
WHERE flag_id = $1 AND subject_id = $2
`

type GetAssignmentParams struct {
	FlagID    pgtype.UUID `db:"flag_id" json:"flag_id"`
	SubjectID string      `db:"subject_id" json:"subject_id"`
}

func (q *Queries) GetAssignment(ctx context.Context, arg GetAssignmentParams) (FlagAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, arg.FlagID, arg.SubjectID)
	var i FlagAssignment
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.SubjectID,
		&i.Bucket,
		&i.ChosenVariant,
		&i.AssignedAt,
	)
	return i, err
}

const upsertAssignment = `-- name: UpsertAssignment :one
INSERT INTO flag_assignments (flag_id, subject_id, bucket, chosen_variant) 
VALUES ($1, $2, $3, $4)
ON CONFLICT (flag_id, subject_id) 
DO UPDATE SET 
    bucket = EXCLUDED.bucket,
    chosen_variant = EXCLUDED.chosen_variant,
    assigned_at = NOW()
RETURNING id, flag_id, subject_id, bucket, chosen_variant, assigned_at
`

type UpsertAssignmentParams struct {
	FlagID        pgtype.UUID `db:"flag_id" json:"flag_id"`
	SubjectID     string      `db:"subject_id" json:"subject_id"`
	Bucket        int32       `db:"bucket" json:"bucket"`
	ChosenVariant []byte      `db:"chosen_variant" json:"chosen_variant"`
}

func (q *Queries) UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) (FlagAssignment, error) {
	row := q.db.QueryRow(ctx, upsertAssignment,
		arg.FlagID,
		arg.SubjectID,
		arg.Bucket,
		arg.ChosenVariant,
	)
	var i FlagAssignment
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.SubjectID,
		&i.Bucket,
		&i.ChosenVariant,
		&i.AssignedAt,
	)
	return i, err
}
