// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlag = `-- name: CreateFlag :one
INSERT INTO flags (tenant_id, key, description, type, enabled, salt) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, tenant_id, key, description, type, enabled, salt, created_at, updated_at
`

type CreateFlagParams struct {
	TenantID    pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Key         string      `db:"key" json:"key"`
	Description pgtype.Text `db:"description" json:"description"`
	Type        FlagType    `db:"type" json:"type"`
	Enabled     pgtype.Bool `db:"enabled" json:"enabled"`
	Salt        string      `db:"salt" json:"salt"`
}

func (q *Queries) CreateFlag(ctx context.Context, arg CreateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, createFlag,
		arg.TenantID,
		arg.Key,
		arg.Description,
		arg.Type,
		arg.Enabled,
		arg.Salt,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Description,
		&i.Type,
		&i.Enabled,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlagByTenantKey = `-- name: GetFlagByTenantKey :one
SELECT id, tenant_id, key, description, type, enabled, salt, created_at, updated_at
FROM flags 
WHERE tenant_id = $1 AND key = $2
`

type GetFlagByTenantKeyParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Key      string      `db:"key" json:"key"`
}

func (q *Queries) GetFlagByTenantKey(ctx context.Context, arg GetFlagByTenantKeyParams) (Flag, error) {
	row := q.db.QueryRow(ctx, getFlagByTenantKey, arg.TenantID, arg.Key)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Description,
		&i.Type,
		&i.Enabled,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlagsByTenant = `-- name: ListFlagsByTenant :many
SELECT id, tenant_id, key, description, type, enabled, salt, created_at, updated_at FROM flags 
WHERE tenant_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) ListFlagsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Flag, error) {
	rows, err := q.db.Query(ctx, listFlagsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flag{}
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Key,
			&i.Description,
			&i.Type,
			&i.Enabled,
			&i.Salt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlag = `-- name: UpdateFlag :one
UPDATE flags 
SET enabled = COALESCE($3, enabled),
    salt = COALESCE($4, salt),
    description = COALESCE($5, description)
WHERE tenant_id = $1 AND key = $2
RETURNING id, tenant_id, key, description, type, enabled, salt, created_at, updated_at
`

type UpdateFlagParams struct {
	TenantID    pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Key         string      `db:"key" json:"key"`
	Enabled     pgtype.Bool `db:"enabled" json:"enabled"`
	Salt        string      `db:"salt" json:"salt"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) UpdateFlag(ctx context.Context, arg UpdateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, updateFlag,
		arg.TenantID,
		arg.Key,
		arg.Enabled,
		arg.Salt,
		arg.Description,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Description,
		&i.Type,
		&i.Enabled,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
