// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldIdempotencyKeys = `-- name: CleanupOldIdempotencyKeys :exec
DELETE FROM idempotency_keys 
WHERE created_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) CleanupOldIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldIdempotencyKeys)
	return err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (tenant_id, key, method, path_hash, status) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING tenant_id, key, method, path_hash, status, created_at
`

type CreateIdempotencyKeyParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Key      pgtype.UUID `db:"key" json:"key"`
	Method   string      `db:"method" json:"method"`
	PathHash []byte      `db:"path_hash" json:"path_hash"`
	Status   int32       `db:"status" json:"status"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.TenantID,
		arg.Key,
		arg.Method,
		arg.PathHash,
		arg.Status,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.TenantID,
		&i.Key,
		&i.Method,
		&i.PathHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT tenant_id, key, method, path_hash, status, created_at FROM idempotency_keys 
WHERE tenant_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Key      pgtype.UUID `db:"key" json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.TenantID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.TenantID,
		&i.Key,
		&i.Method,
		&i.PathHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateIdempotencyStatus = `-- name: UpdateIdempotencyStatus :exec
UPDATE idempotency_keys
SET status = $3
WHERE tenant_id = $1 AND key = $2
`

type UpdateIdempotencyStatusParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Key      pgtype.UUID `db:"key" json:"key"`
	Status   int32       `db:"status" json:"status"`
}

func (q *Queries) UpdateIdempotencyStatus(ctx context.Context, arg UpdateIdempotencyStatusParams) error {
	_, err := q.db.Exec(ctx, updateIdempotencyStatus, arg.TenantID, arg.Key, arg.Status)
	return err
}
