// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ExperimentStatus string

const (
	ExperimentStatusDraft   ExperimentStatus = "draft"
	ExperimentStatusRunning ExperimentStatus = "running"
	ExperimentStatusPaused  ExperimentStatus = "paused"
	ExperimentStatusStopped ExperimentStatus = "stopped"
)

func (e *ExperimentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExperimentStatus(s)
	case string:
		*e = ExperimentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExperimentStatus: %T", src)
	}
	return nil
}

type NullExperimentStatus struct {
	ExperimentStatus ExperimentStatus `json:"experiment_status"`
	Valid            bool             `json:"valid"` // Valid is true if ExperimentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExperimentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExperimentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExperimentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExperimentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExperimentStatus), nil
}

type FlagType string

const (
	FlagTypeBoolean FlagType = "boolean"
	FlagTypeJson    FlagType = "json"
)

func (e *FlagType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlagType(s)
	case string:
		*e = FlagType(s)
	default:
		return fmt.Errorf("unsupported scan type for FlagType: %T", src)
	}
	return nil
}

type NullFlagType struct {
	FlagType FlagType `json:"flag_type"`
	Valid    bool     `json:"valid"` // Valid is true if FlagType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlagType) Scan(value interface{}) error {
	if value == nil {
		ns.FlagType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlagType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlagType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlagType), nil
}

type ApiKey struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Name       string             `db:"name" json:"name"`
	SecretEnc  []byte             `db:"secret_enc" json:"secret_enc"`
	Active     pgtype.Bool        `db:"active" json:"active"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

type Experiment struct {
	ID        pgtype.UUID          `db:"id" json:"id"`
	TenantID  pgtype.UUID          `db:"tenant_id" json:"tenant_id"`
	Key       string               `db:"key" json:"key"`
	FlagID    pgtype.UUID          `db:"flag_id" json:"flag_id"`
	Status    NullExperimentStatus `db:"status" json:"status"`
	Traffic   int32                `db:"traffic" json:"traffic"`
	CreatedAt pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz   `db:"updated_at" json:"updated_at"`
}

type ExperimentVariant struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	ExperimentID pgtype.UUID `db:"experiment_id" json:"experiment_id"`
	Name         string      `db:"name" json:"name"`
	Weight       int32       `db:"weight" json:"weight"`
	Config       []byte      `db:"config" json:"config"`
}

type Flag struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Key         string             `db:"key" json:"key"`
	Description pgtype.Text        `db:"description" json:"description"`
	Type        FlagType           `db:"type" json:"type"`
	Enabled     pgtype.Bool        `db:"enabled" json:"enabled"`
	Salt        string             `db:"salt" json:"salt"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type FlagAssignment struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	FlagID        pgtype.UUID        `db:"flag_id" json:"flag_id"`
	SubjectID     string             `db:"subject_id" json:"subject_id"`
	Bucket        int32              `db:"bucket" json:"bucket"`
	ChosenVariant []byte             `db:"chosen_variant" json:"chosen_variant"`
	AssignedAt    pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
}

type FlagRule struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	FlagID    pgtype.UUID        `db:"flag_id" json:"flag_id"`
	Priority  int32              `db:"priority" json:"priority"`
	Rollout   int32              `db:"rollout" json:"rollout"`
	Variant   []byte             `db:"variant" json:"variant"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type IdempotencyKey struct {
	TenantID  pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Key       pgtype.UUID        `db:"key" json:"key"`
	Method    string             `db:"method" json:"method"`
	PathHash  []byte             `db:"path_hash" json:"path_hash"`
	Status    int32              `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Outbox struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Topic       string             `db:"topic" json:"topic"`
	Key         pgtype.Text        `db:"key" json:"key"`
	Payload     []byte             `db:"payload" json:"payload"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
