// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOutbox = `-- name: AddOutbox :one
INSERT INTO outbox (tenant_id, topic, key, payload) 
VALUES ($1, $2, $3, $4) 
RETURNING id, tenant_id, topic, key, payload, created_at, published_at
`

type AddOutboxParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Topic    string      `db:"topic" json:"topic"`
	Key      pgtype.Text `db:"key" json:"key"`
	Payload  []byte      `db:"payload" json:"payload"`
}

func (q *Queries) AddOutbox(ctx context.Context, arg AddOutboxParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, addOutbox,
		arg.TenantID,
		arg.Topic,
		arg.Key,
		arg.Payload,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
SELECT id, tenant_id, topic, key, payload, created_at, published_at FROM outbox 
WHERE published_at IS NULL 
ORDER BY created_at ASC 
LIMIT $1 
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimOutboxBatch(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox 
SET published_at = NOW() 
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, dollar_1)
	return err
}
