// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOutbox(ctx context.Context, arg AddOutboxParams) (Outbox, error)
	ClaimOutboxBatch(ctx context.Context, limit int32) ([]Outbox, error)
	CleanupOldIdempotencyKeys(ctx context.Context) error
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateExperiment(ctx context.Context, arg CreateExperimentParams) (Experiment, error)
	CreateExperimentVariant(ctx context.Context, arg CreateExperimentVariantParams) (ExperimentVariant, error)
	CreateFlag(ctx context.Context, arg CreateFlagParams) (Flag, error)
	CreateFlagRule(ctx context.Context, arg CreateFlagRuleParams) (FlagRule, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	DeleteFlagRule(ctx context.Context, arg DeleteFlagRuleParams) error
	GetAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetAPIKeyByTenant(ctx context.Context, arg GetAPIKeyByTenantParams) (ApiKey, error)
	GetAssignment(ctx context.Context, arg GetAssignmentParams) (FlagAssignment, error)
	GetExperimentByFlagID(ctx context.Context, flagID pgtype.UUID) (Experiment, error)
	GetExperimentByTenantKey(ctx context.Context, arg GetExperimentByTenantKeyParams) (Experiment, error)
	GetFlagByTenantKey(ctx context.Context, arg GetFlagByTenantKeyParams) (Flag, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetRulesByFlag(ctx context.Context, flagID pgtype.UUID) ([]FlagRule, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetVariantsByExperiment(ctx context.Context, experimentID pgtype.UUID) ([]ExperimentVariant, error)
	ListExperimentsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Experiment, error)
	ListFlagsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Flag, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	MarkOutboxPublished(ctx context.Context, dollar_1 []pgtype.UUID) error
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateExperimentStatus(ctx context.Context, arg UpdateExperimentStatusParams) (Experiment, error)
	UpdateExperimentVariant(ctx context.Context, arg UpdateExperimentVariantParams) (ExperimentVariant, error)
	UpdateFlag(ctx context.Context, arg UpdateFlagParams) (Flag, error)
	UpdateFlagRule(ctx context.Context, arg UpdateFlagRuleParams) (FlagRule, error)
	UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) (FlagAssignment, error)
}

var _ Querier = (*Queries)(nil)
